name: Package and Release IP

on:
  push:
    branches:
      - main

jobs:
  package-ip:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Vivado
        run: |
          echo "Runner con Vivado instalado"

      - name: Package IP with Vivado
        run: |
          vivado -mode batch -source scripts/packager_adder.tcl


      - name: Upload IP artifact
        uses: actions/upload-artifact@v4
        with:
          name: adder_v1_0
          path: packaged_ip/adder_v1_0
